line-length = 120
indent-width = 4
# indent-style = "space"
# docstring-code-format = true

[lint]
select = ["E", "F"]
ignore = ["F401"]

[format]
quote-style = "double"
indent-style = "tab"
line-ending = "native"
docstring-code-format = true
docstring-code-line-length = "dynamic"
